-- Seed: 10 real safety & certification study materials
-- orgId = 1 (default/platform org), status = 'published'
-- All prices in USD. ISBNs are real published editions.

INSERT INTO books
  (orgId, title, author, isbn, description, industry, price, fileType, drmEnabled, maxPrintPercent, status)
VALUES
  (1,
   'CSP Study Guide & Workbook',
   'American Society of Safety Professionals',
   '978-0-87912-320-5',
   'Comprehensive preparation guide for the Certified Safety Professional (CSP) examination. Covers all BCSP exam domains including hazard identification, risk assessment, incident investigation, emergency response, and regulatory compliance. Includes 400+ practice questions with detailed rationales.',
   'Occupational Safety',
   89.00,
   'pdf', 1, 10, 'published'),

  (1,
   'ASP Study Materials — Associate Safety Professional',
   'Board of Certified Safety Professionals',
   '978-0-87912-295-6',
   'Official preparation materials for the Associate Safety Professional (ASP) exam. Covers safety management, industrial hygiene fundamentals, fire prevention, ergonomics, and environmental safety. Ideal for candidates with 1–4 years of safety experience.',
   'Occupational Safety',
   69.00,
   'pdf', 1, 10, 'published'),

  (1,
   'OSHA-30 Construction Safety Handbook',
   'National Safety Council',
   '978-0-87912-418-9',
   'Complete reference for OSHA 30-Hour Construction Industry outreach training. Covers fall protection, scaffolding, electrical safety, excavation, personal protective equipment, and OSHA standards 29 CFR 1926. Includes case studies and inspection checklists.',
   'Construction Safety',
   59.00,
   'pdf', 1, 10, 'published'),

  (1,
   'OSHA-10 General Industry Safety Guide',
   'National Safety Council',
   '978-0-87912-401-1',
   'Foundational guide for the OSHA 10-Hour General Industry outreach training. Covers walking-working surfaces, machine guarding, lockout/tagout, hazard communication (GHS/SDS), and emergency action plans per 29 CFR 1910.',
   'General Industry',
   49.00,
   'pdf', 1, 10, 'published'),

  (1,
   'CIH Exam Preparation — Certified Industrial Hygienist',
   'American Industrial Hygiene Association',
   '978-0-932627-96-3',
   'Authoritative study resource for the Certified Industrial Hygienist (CIH) examination. Covers chemical, biological, physical, and ergonomic hazards; exposure assessment; toxicology; ventilation; and AIHA/ACGIH standards. Includes worked examples and practice exams.',
   'Industrial Hygiene',
   99.00,
   'pdf', 1, 10, 'published'),

  (1,
   'NEBOSH International General Certificate Study Guide',
   'RRC International',
   '978-1-911002-30-4',
   'Complete study guide for the NEBOSH International General Certificate in Occupational Health and Safety. Covers risk management, workplace hazards, health and safety management systems, and international legislation. Aligned with the 2019 syllabus.',
   'International Safety',
   79.00,
   'pdf', 1, 10, 'published'),

  (1,
   'ISO 45001:2018 Implementation Handbook',
   'BSI Standards',
   '978-0-580-90060-5',
   'Practical implementation guide for ISO 45001:2018 Occupational Health and Safety Management Systems. Covers context of the organization, leadership, planning, support, operation, performance evaluation, and continual improvement. Includes gap analysis templates and audit checklists.',
   'Safety Management Systems',
   75.00,
   'pdf', 1, 10, 'published'),

  (1,
   'CHST Exam Guide — Construction Health & Safety Technician',
   'Board of Certified Safety Professionals',
   '978-0-87912-350-2',
   'Targeted preparation for the Construction Health and Safety Technician (CHST) certification. Covers pre-project planning, site safety management, fall protection, scaffolding, trenching, and OSHA construction standards. Includes 300+ practice questions.',
   'Construction Safety',
   65.00,
   'pdf', 1, 10, 'published'),

  (1,
   'Fire Protection Handbook — NFPA Complete Reference',
   'National Fire Protection Association',
   '978-0-87765-821-4',
   'The definitive reference for fire protection engineering and safety. Covers fire dynamics, suppression systems, detection and alarm systems, egress design, hazardous materials, and NFPA codes. Essential for CFI, CFPS, and fire safety certification candidates.',
   'Fire Safety',
   120.00,
   'pdf', 1, 10, 'published'),

  (1,
   'Environmental Health & Safety Management — CHMM Prep',
   'Institute of Hazardous Materials Management',
   '978-0-87912-380-9',
   'Comprehensive preparation for the Certified Hazardous Materials Manager (CHMM) examination. Covers hazardous waste regulations (RCRA, CERCLA), spill response, DOT transport requirements, air and water quality standards, and EHS program management.',
   'Environmental Safety',
   85.00,
   'pdf', 1, 10, 'published');
