CREATE TABLE `attempt_anomaly_summaries` (
	`id` int AUTO_INCREMENT NOT NULL,
	`attemptId` int NOT NULL,
	`candidateId` int NOT NULL,
	`examId` int NOT NULL,
	`orgId` int NOT NULL,
	`totalAnomalies` int NOT NULL DEFAULT 0,
	`tooFastCount` int NOT NULL DEFAULT 0,
	`tooSlowCount` int NOT NULL DEFAULT 0,
	`collusionCount` int NOT NULL DEFAULT 0,
	`uniformSpeedCount` int NOT NULL DEFAULT 0,
	`riskScore` decimal(5,2) NOT NULL DEFAULT '0.00',
	`riskLevel` enum('clean','low','medium','high','critical') NOT NULL DEFAULT 'clean',
	`totalTimeMs` int NOT NULL DEFAULT 0,
	`meanResponseTimeMs` int NOT NULL DEFAULT 0,
	`stdDevResponseTimeMs` int NOT NULL DEFAULT 0,
	`fastestResponseMs` int,
	`slowestResponseMs` int,
	`flaggedForReview` boolean NOT NULL DEFAULT false,
	`analysisCompletedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `attempt_anomaly_summaries_id` PRIMARY KEY(`id`),
	CONSTRAINT `attempt_anomaly_summaries_attemptId_unique` UNIQUE(`attemptId`)
);
--> statement-breakpoint
CREATE TABLE `question_responses` (
	`id` int AUTO_INCREMENT NOT NULL,
	`attemptId` int NOT NULL,
	`questionId` int NOT NULL,
	`candidateId` int NOT NULL,
	`examId` int NOT NULL,
	`orgId` int NOT NULL,
	`responseTimeMs` int NOT NULL,
	`flaggedForReview` boolean DEFAULT false,
	`revisitCount` int NOT NULL DEFAULT 0,
	`answer` json,
	`isCorrect` boolean,
	`questionIndex` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `question_responses_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `response_time_anomalies` (
	`id` int AUTO_INCREMENT NOT NULL,
	`attemptId` int NOT NULL,
	`questionId` int NOT NULL,
	`candidateId` int NOT NULL,
	`examId` int NOT NULL,
	`orgId` int NOT NULL,
	`anomalyType` enum('too_fast','too_slow','iqr_outlier_fast','iqr_outlier_slow','collusion','uniform_speed','acceleration','copy_pattern') NOT NULL,
	`severity` enum('low','medium','high','critical') NOT NULL,
	`responseTimeMs` int NOT NULL,
	`meanTimeMs` int NOT NULL,
	`stdDevMs` int NOT NULL,
	`zScore` decimal(8,4) NOT NULL,
	`iqrLowerBound` int,
	`iqrUpperBound` int,
	`collusionAttemptId` int,
	`collusionSimilarityScore` decimal(5,4),
	`aiNarrative` text,
	`reviewStatus` enum('pending','confirmed','dismissed') NOT NULL DEFAULT 'pending',
	`reviewedBy` int,
	`reviewedAt` timestamp,
	`reviewNote` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `response_time_anomalies_id` PRIMARY KEY(`id`)
);
